const KEY='toeic950MissionV3';
const OLD_KEY='toeic950MissionV2';
function fresh(){return{version:APP_VERSION,settings:{score:720,minutes:60,listen:'',read:''},dailyStats:{},history:{},diag:{list:[],i:0,correct:0,byPart:{},answers:[],currentAnswered:false,audioPlayed:{}},practice:{total:0,correct:0,partStats:{}},errors:[],vocabKnown:[],vocabSeen:{}}}
function load(){
  try{
    const current=JSON.parse(localStorage.getItem(KEY)||'null');
    if(current)return Object.assign(fresh(),current,{version:APP_VERSION});
    const old=JSON.parse(localStorage.getItem(OLD_KEY)||'null');
    if(old){const n=fresh();n.settings=Object.assign(n.settings,old.settings||{});n.errors=old.errors||[];n.vocabKnown=old.vocabKnown||[];n.practice.total=old.practice?.total||0;n.practice.correct=old.practice?.correct||0;return n}
  }catch(e){}
  return fresh();
}
let data=load();
let vIndex=0;
let practice={list:[],i:0,correct:0,start:0,timer:null,answered:false,answers:[],audioPlayed:{},currentStarted:0,mode:'training',part:5};
function save(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}}
function today(){return new Date().toLocaleDateString('en-CA')}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function daily(){const t=today();if(!data.dailyStats[t])data.dailyStats[t]={part5:0,listening:0,part7:0,errorsReviewed:0,vocabWords:[],questions:0,seconds:0};return data.dailyStats[t]}
function effectiveStreak(){let n=0;for(let i=0;i<365;i++){const d=new Date();d.setDate(d.getDate()-i);const k=d.toLocaleDateString('en-CA');if((data.history[k]||0)>0)n++;else if(i===0)continue;else break}return n}
function initDay(){document.getElementById('streak').textContent=effectiveStreak()+' 天'}
function greeting(){const h=new Date().getHours();document.getElementById('topTitle').textContent=(h<12?'Good morning':h<18?'Good afternoon':'Good evening')+', Steven.'}
function go(id){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));document.body.classList.toggle('focus-mode',['practice','diagnostic'].includes(id));window.scrollTo({top:0,behavior:'smooth'});if(id==='errors')renderErrors();if(id==='progress')renderProgress();if(id==='home')renderTasks()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.go));
function saveSettings(){data.settings.score=+document.getElementById('currentScore').value||720;data.settings.minutes=+document.getElementById('dailyMinutes').value||60;data.settings.listen=document.getElementById('listenScore').value;data.settings.read=document.getElementById('readScore').value;save();renderTasks()}
function loadSettings(){document.getElementById('currentScore').value=data.settings.score||720;document.getElementById('dailyMinutes').value=data.settings.minutes||60;document.getElementById('listenScore').value=data.settings.listen||'';document.getElementById('readScore').value=data.settings.read||''}
function updateScoreUI(){const s=+document.getElementById('currentScore').value||720;document.getElementById('heroCurrent').textContent=s;document.getElementById('gapScore').textContent=Math.max(0,950-s);const pct=clamp((s-720)/(950-720)*100,0,100);document.getElementById('goalProgress').style.width=pct+'%';document.querySelectorAll('.step').forEach(x=>x.classList.remove('current','done'));const vals=[720,800,850,900,950];let marked=false;document.querySelectorAll('.step').forEach((el,i)=>{if(vals[i]<s)el.classList.add('done');else if(!marked){el.classList.add('current');marked=true}})}
function taskTargets(min){if(min===30)return[{k:'part5',name:'Part 5 速度訓練',target:8,unit:'題'},{k:'listening',name:'Listening Part 2–4',target:6,unit:'題'},{k:'errorsReviewed',name:'錯題重看',target:2,unit:'題'},{k:'vocab',name:'950 單字',target:4,unit:'字'}];if(min===90)return[{k:'part5',name:'Part 5 高強度',target:20,unit:'題'},{k:'listening',name:'Listening 精聽',target:18,unit:'題'},{k:'part7',name:'Part 7 限時閱讀',target:15,unit:'題'},{k:'errorsReviewed',name:'錯題重看',target:8,unit:'題'},{k:'vocab',name:'950 單字',target:10,unit:'字'}];return[{k:'part5',name:'Part 5 速度訓練',target:12,unit:'題'},{k:'listening',name:'Listening Part 2–4',target:10,unit:'題'},{k:'part7',name:'Part 7 限時閱讀',target:8,unit:'題'},{k:'errorsReviewed',name:'錯題重看',target:5,unit:'題'},{k:'vocab',name:'950 單字',target:5,unit:'字'}]}
function taskValue(k,d){return k==='vocab'?(d.vocabWords||[]).length:(d[k]||0)}
function updateHistory(){const d=daily(),targets=taskTargets(+data.settings.minutes||60);const ratios=targets.map(t=>clamp(taskValue(t.k,d)/t.target,0,1));const pct=Math.round(ratios.reduce((a,b)=>a+b,0)/ratios.length*100);data.history[today()]=pct;save();initDay();return pct}
function renderTasks(){const min=+document.getElementById('dailyMinutes').value||60,d=daily(),targets=taskTargets(min);document.getElementById('taskList').innerHTML=targets.map(t=>{const v=taskValue(t.k,d),pct=Math.round(clamp(v/t.target,0,1)*100),done=pct>=100;return `<div class="auto-task"><div><b>${t.name}</b><small>${v} / ${t.target} ${t.unit} · 由實際作答自動累計</small></div><span class="task-status ${done?'done':'todo'}">${done?'✓ 完成':pct+'%'}</span><div class="task-meter"><div style="width:${pct}%"></div></div></div>`}).join('');const pct=updateHistory();document.getElementById('todayPct').textContent=pct+'%';document.getElementById('todayBar').style.width=pct+'%';document.getElementById('dailyAdvice').textContent=pct===100?'今日訓練達標。最後看一次錯題，確認今天最常見的錯因。':pct>=60?'進度不錯。剩餘時間優先補完成率最低的項目。':'今天的任務會由真實作答自動累計，不再靠手動勾選。'}
function renderParts(){document.getElementById('partCards').innerHTML=PARTS.map(p=>`<div class="panel part-card"><div class="num">${p.n}</div><span class="tag">Part ${p.n}</span><h3>${p.zh}</h3><p><b>${p.name}</b><br>${p.focus}</p><ul>${p.tips.map(t=>`<li>${t}</li>`).join('')}</ul>${p.n>1?`<div class="actions"><button class="btn btn-soft" onclick="document.getElementById('practicePart').value='${p.n}';go('practice');resetPractice()">練這一 Part</button></div>`:''}</div>`).join('')}
function chosenDifficulty(){const v=document.getElementById('practiceDifficulty')?.value||'adaptive';if(v!=='adaptive')return +v;const s=+data.settings.score||720;if(s<800)return 720;if(s<880)return 800;if(s<930)return 900;return 950}
function difficultyPool(part,level,count=10){const all=QUESTIONS[part]||[];let primary;if(level===720)primary=all.filter(q=>q.difficulty<=800);else if(level===800)primary=all.filter(q=>q.difficulty>=800&&q.difficulty<=900);else if(level===900)primary=all.filter(q=>q.difficulty>=900);else primary=all.filter(q=>q.difficulty>=950);const fallback=level===950?all.filter(q=>q.difficulty>=900):level===900?all.filter(q=>q.difficulty>=800):all;const seen=new Set(),pool=[];for(const item of [...shuffle(primary),...shuffle(fallback),...shuffle(all)]){if(!seen.has(item.id)){seen.add(item.id);pool.push(item)}if(pool.length>=count)break}return pool}
function prepareQuestion(q){const pairs=shuffle(q.opts.map((text,i)=>({text,ok:i===q.a})));const n={...q,opts:pairs.map(x=>x.text),a:pairs.findIndex(x=>x.ok)};if(q.part===2){n.spoken=q.prompt+' A. '+n.opts[0]+' B. '+n.opts[1]+' C. '+n.opts[2];n.transcript=n.spoken}return n}
function groupedPick(part,pool,count){if(![3,4,7].includes(part))return shuffle(pool).slice(0,count);const key=part===7?'passage':'spoken',groups={};pool.forEach(x=>(groups[x[key]]??=[]).push(x));let out=[];for(const g of shuffle(Object.values(groups))){out.push(...g);if(out.length>=count)break}return out.slice(0,count)}
function speak(txt,rate=.9){if(!('speechSynthesis'in window)){alert('瀏覽器不支援語音播放，建議 Chrome 或 Edge。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(txt);u.lang='en-US';u.rate=rate;const voices=speechSynthesis.getVoices().filter(v=>/^en(-|_)/i.test(v.lang));if(voices.length)u.voice=voices.find(v=>/US/i.test(v.lang))||voices[0];speechSynthesis.speak(u)}
function focusQuestionBox(id){requestAnimationFrame(()=>{const el=document.getElementById(id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})})}
function optionButtons(q,handler,part2Hidden=false){if(part2Hidden)return `<div class="part2-answer-list">${q.opts.map((o,i)=>`<button class="opt" data-index="${i}" onclick="${handler}(${i},this)">${String.fromCharCode(65+i)}</button>`).join('')}</div>`;return `<div class="option-list">${q.opts.map((o,i)=>`<button class="opt" data-index="${i}" onclick="${handler}(${i},this)">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>`}
function questionLayout(q,content,context){const split=q.part===7&&q.passage;const passage=split?`<div class="passage-pane">${q.passage}</div>`:'';return `<div class="qhead"><span>${context} · Part ${q.part}</span><span><span class="difficulty-pill">${q.difficulty}+</span></span></div>${split?`<div class="practice-layout split">${passage}<div class="answer-pane">${content}</div></div>`:content}`}
function playButton(context,q,played,max){if(!q.spoken)return '';const disabled=played>=max;return `<div class="audio-row"><button class="btn btn-primary ${disabled?'audio-disabled':''}" ${disabled?'disabled':''} onclick="${context==='practice'?'playPracticeAudio()':'playDiagAudio()'}">▶ 播放 Listening</button><span class="play-count">${max===1?`限播 1 次 · ${played}/1`:`已播放 ${played} 次`}</span></div>`}
