const KEY='toeic950MissionV2';
function fresh(){return{settings:{score:720,minutes:60,listen:'',read:''},tasks:{},history:{},streak:1,lastDay:'',diag:{i:0,correct:0,byPart:{},answers:[]},practice:{total:0,correct:0},errors:[],vocabKnown:[],reviewed:0};}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return fresh()}}
let data=load();let vIndex=0;let practice={list:[],i:0,correct:0,start:0,timer:null,answered:false};
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function today(){return new Date().toLocaleDateString('en-CA')}
function initDay(){const t=today();if(data.lastDay!==t){if(data.lastDay){const d1=new Date(data.lastDay),d2=new Date(t);const diff=Math.round((d2-d1)/86400000);data.streak=diff===1?(data.streak||0)+1:1}else data.streak=1;data.lastDay=t;save()}document.getElementById('streak').textContent=(data.streak||1)+' 天'}
function greeting(){const h=new Date().getHours();document.getElementById('topTitle').textContent=(h<12?'Good morning':h<18?'Good afternoon':'Good evening')+', Steven.'}
function go(id){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));document.body.classList.toggle('focus-mode',['practice','diagnostic'].includes(id));window.scrollTo({top:0,behavior:'smooth'});if(id==='errors')renderErrors();if(id==='progress')renderProgress()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.go));
function saveSettings(){data.settings.score=+document.getElementById('currentScore').value||720;data.settings.minutes=+document.getElementById('dailyMinutes').value||60;data.settings.listen=document.getElementById('listenScore').value;data.settings.read=document.getElementById('readScore').value;save()}
function loadSettings(){document.getElementById('currentScore').value=data.settings.score||720;document.getElementById('dailyMinutes').value=data.settings.minutes||60;document.getElementById('listenScore').value=data.settings.listen||'';document.getElementById('readScore').value=data.settings.read||''}
function updateScoreUI(){const s=+document.getElementById('currentScore').value||720;document.getElementById('heroCurrent').textContent=s;document.getElementById('gapScore').textContent=Math.max(0,950-s);const pct=Math.max(0,Math.min(100,(s-720)/(950-720)*100));document.getElementById('goalProgress').style.width=pct+'%';document.querySelectorAll('.step').forEach(x=>x.classList.remove('current','done'));const vals=[720,800,850,900,950];document.querySelectorAll('.step').forEach((el,i)=>{if(vals[i]<s)el.classList.add('done');else if(vals[i]>=s&&!document.querySelector('.step.current'))el.classList.add('current')})}
function taskTemplate(min){if(min===30)return[['Part 5 速度訓練','10 分鐘：詞性 / 文法 / 搭配'],['Listening 跟讀','10 分鐘：Part 2 或 Part 3'],['錯題複習','5 分鐘：昨天錯題重做'],['950 單字','5 分鐘：5 個高頻商務字']];if(min===90)return[['Part 5 速度訓練','20 分鐘：文法與單字'],['Listening 精聽＋跟讀','25 分鐘：Part 2–4'],['Part 7 限時閱讀','25 分鐘：定位＋同義改寫'],['錯題本','10 分鐘：分類錯因並重做'],['950 單字','10 分鐘：10 個字＋搭配']];return[['Part 5 速度訓練','15 分鐘：文法與單字'],['Listening 精聽＋跟讀','15 分鐘：Part 2–4'],['Part 7 限時閱讀','15 分鐘：定位＋同義改寫'],['錯題本','10 分鐘：錯題重做'],['950 單字','5 分鐘：5 個字＋搭配']];}
function renderTasks(){const min=+document.getElementById('dailyMinutes').value||60,ts=taskTemplate(min),t=today();if(!data.tasks[t]||data.tasks[t].length!==ts.length)data.tasks[t]=Array(ts.length).fill(false);document.getElementById('taskList').innerHTML=ts.map((x,i)=>`<label class="task ${data.tasks[t][i]?'done':''}"><input type="checkbox" ${data.tasks[t][i]?'checked':''} onchange="toggleTask(${i},this.checked)"><span><b>${x[0]}</b><small>${x[1]}</small></span></label>`).join('');updateToday();save()}
function toggleTask(i,val){const t=today();data.tasks[t][i]=val;const n=data.tasks[t].filter(Boolean).length;data.history[t]=Math.round(n/data.tasks[t].length*100);save();renderTasks()}
function updateToday(){const arr=data.tasks[today()]||[],pct=arr.length?Math.round(arr.filter(Boolean).length/arr.length*100):0;document.getElementById('todayPct').textContent=pct+'%';document.getElementById('todayBar').style.width=pct+'%';document.getElementById('dailyAdvice').textContent=pct===100?'今日任務完成。最後花 2 分鐘回想：今天最容易錯的是哪一種題型？':pct>=50?'已完成一半以上。剩下的時間優先做「最不想做」的弱項。':'高分訓練從固定節奏開始。先做一個 15 分鐘區塊。'}
function renderParts(){document.getElementById('partCards').innerHTML=PARTS.map(p=>`<div class="panel part-card"><div class="num">${p.n}</div><span class="tag">Part ${p.n}</span><h3>${p.zh}</h3><p><b>${p.name}</b><br>${p.focus}</p><ul>${p.tips.map(t=>`<li>${t}</li>`).join('')}</ul>${p.n>1?`<div class="actions"><button class="btn btn-soft" onclick="document.getElementById('practicePart').value='${p.n}';go('practice');resetPractice()">練這一 Part</button></div>`:''}</div>`).join('')}
function speak(txt,rate=.78){if(!('speechSynthesis'in window)){alert('瀏覽器不支援語音播放，建議 Chrome 或 Edge。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(txt);u.lang='en-US';u.rate=rate;speechSynthesis.speak(u)}
function focusQuestionBox(id){requestAnimationFrame(()=>{const el=document.getElementById(id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});})}
function startDiagnostic(){document.getElementById('diagBox').classList.remove('hidden');renderDiag();focusQuestionBox('diagBox')}
function renderDiag(){if(data.diag.i>=DIAG.length){finishDiag();return}const q=DIAG[data.diag.i],listen=q.part<=4;document.getElementById('diagBox').innerHTML=`<div class="qhead"><span>診斷 ${data.diag.i+1} / ${DIAG.length} · Part ${q.part}</span><span>${listen?'Listening':'Reading'}</span></div>${q.passage?`<div class="example" style="white-space:pre-line">${q.passage}</div>`:''}${listen?`<div class="actions"><button class="btn btn-primary" onclick="speak(${JSON.stringify(q.spoken)},.82)">▶ 播放題目</button></div>`:''}<div class="question">${listen&&q.part===2?'選出最適當的回答。':q.prompt}</div><div class="option-list">${q.opts.map((o,i)=>`<button class="opt" onclick="answerDiag(${i},this)">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="diagFeedback"></div>`;focusQuestionBox('diagBox')}
function answerDiag(i,btn){const q=DIAG[data.diag.i],ok=i===q.a;document.querySelectorAll('#diagBox .opt').forEach((b,j)=>{b.disabled=true;if(j===q.a)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');data.diag.correct+=ok?1:0;data.diag.byPart[q.part]=data.diag.byPart[q.part]||{n:0,c:0};data.diag.byPart[q.part].n++;data.diag.byPart[q.part].c+=ok?1:0;data.diag.answers.push({part:q.part,ok});if(!ok)addError(q.part,q.prompt||q.spoken,q.opts[q.a],q.why,q.cause);document.getElementById('diagFeedback').innerHTML=`<div class="feedback"><b>${ok?'✅ 正確':'❌ 答錯'}</b><br>${q.why}</div><div class="actions"><button class="btn btn-primary" onclick="nextDiag()">下一題</button></div>`;save();updateDiagStats()}
function nextDiag(){data.diag.i++;save();renderDiag();updateDiagStats()}
function updateDiagStats(){document.getElementById('diagDone').textContent=Math.min(data.diag.i+(document.querySelector('#diagFeedback .feedback')?1:0),DIAG.length)+' / '+DIAG.length;const n=data.diag.answers.length;document.getElementById('diagAcc').textContent=n?Math.round(data.diag.correct/n*100)+'%':'—'}
function finishDiag(){const entries=Object.entries(data.diag.byPart);let weak=entries.sort((a,b)=>(a[1].c/a[1].n)-(b[1].c/b[1].n))[0];const advice=weak?`目前弱點優先順序：先補 Part ${weak[0]}。診斷正確率約 ${Math.round(data.diag.correct/DIAG.length*100)}%。接下來 7 天，把至少 40% 的練習時間放在 Part ${weak[0]}，直到正確率穩定超過 90%。`:'尚無資料';document.getElementById('diagBox').innerHTML=`<h3>診斷完成</h3><p>${advice}</p><div class="actions"><button class="btn btn-primary" onclick="go('practice')">開始針對性訓練</button><button class="btn btn-soft" onclick="resetDiag()">重新診斷</button></div>`;document.getElementById('diagAdvice').textContent=advice;updateDiagStats()}
function resetDiag(){data.diag={i:0,correct:0,byPart:{},answers:[]};save();updateDiagStats();startDiagnostic()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function resetPractice(){if(practice.timer)clearInterval(practice.timer);practice={list:[],i:0,correct:0,start:0,timer:null,answered:false};document.getElementById('practiceBox').classList.add('hidden');document.getElementById('pracScore').textContent='0 / 0';document.getElementById('pracAcc').textContent='—';document.getElementById('pracTimer').textContent='00:00';document.getElementById('pracMessage').textContent='高分訓練要同時追蹤「準確率」與「速度」。'}
function startPractice(){resetPractice();const p=+document.getElementById('practicePart').value,count=+document.getElementById('practiceCount').value;let pool=QUESTIONS[p]||QUESTIONS[5];while(pool.length<count)pool=pool.concat(QUESTIONS[p]||QUESTIONS[5]);practice.list=shuffle(pool).slice(0,count);practice.start=Date.now();practice.timer=setInterval(updateTimer,1000);document.getElementById('practiceBox').classList.remove('hidden');renderPractice();focusQuestionBox('practiceBox')}
function updateTimer(){const sec=Math.floor((Date.now()-practice.start)/1000);document.getElementById('pracTimer').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function renderPractice(){if(practice.i>=practice.list.length){finishPractice();return}practice.answered=false;const q=practice.list[practice.i],p=+document.getElementById('practicePart').value,listen=p<=4;document.getElementById('practiceBox').innerHTML=`<div class="qhead"><span>第 ${practice.i+1} / ${practice.list.length} 題 · Part ${p}</span><span>${listen?'Listening':'Reading'}</span></div>${q.passage?`<div class="example" style="white-space:pre-line">${q.passage}</div>`:''}${listen?`<div class="actions"><button class="btn btn-primary" onclick="speak(${JSON.stringify(q.spoken)},.85)">▶ 播放</button></div>`:''}<div class="question">${listen&&p===2?'選出最適當的回答。':q.prompt}</div><div class="option-list">${q.opts.map((o,i)=>`<button class="opt" onclick="answerPractice(${i},this)">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="pracFeedback"></div>`;focusQuestionBox('practiceBox')}
function answerPractice(i,btn){if(practice.answered)return;practice.answered=true;const q=practice.list[practice.i],p=+document.getElementById('practicePart').value,ok=i===q.a;document.querySelectorAll('#practiceBox .opt').forEach((b,j)=>{b.disabled=true;if(j===q.a)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');if(ok)practice.correct++;else addError(p,q.prompt||q.spoken,q.opts[q.a],q.why,q.cause);data.practice.total++;data.practice.correct+=ok?1:0;save();document.getElementById('pracFeedback').innerHTML=`<div class="feedback"><b>${ok?'✅ 正確':'❌ 答錯'}</b><br>${q.why}<br><span class="pill">錯因類型：${q.cause}</span></div><div class="actions"><button class="btn btn-primary" onclick="nextPractice()">下一題</button></div>`;updatePracticeStats()}
function nextPractice(){practice.i++;renderPractice()}
function updatePracticeStats(){const done=practice.i+(practice.answered?1:0);document.getElementById('pracScore').textContent=practice.correct+' / '+done;document.getElementById('pracAcc').textContent=done?Math.round(practice.correct/done*100)+'%':'—'}
function finishPractice(){if(practice.timer)clearInterval(practice.timer);updateTimer();const n=practice.list.length,acc=Math.round(practice.correct/n*100);document.getElementById('practiceBox').innerHTML=`<h3>本輪完成：${practice.correct} / ${n}</h3><p>正確率 ${acc}%</p><div class="callout">${acc>=90?'準確率已達高分訓練區。下一輪縮短時間，保持 90% 以上。':acc>=80?'接近高分區。先把錯題放進錯題本重做，再挑戰同一 Part。':'先不要追速度。把錯因分清楚，正確率拉到 85–90% 後再限時。'}</div><div class="actions"><button class="btn btn-primary" onclick="startPractice()">再練一輪</button><button class="btn btn-soft" onclick="go('errors')">看錯題</button></div>`;document.getElementById('pracMessage').textContent=`本輪 Part ${document.getElementById('practicePart').value}：${acc}%`}
function addError(part,q,ans,why,cause){data.errors.unshift({id:Date.now()+Math.random(),part,q,ans,why,cause,date:today(),reviewed:false});if(data.errors.length>100)data.errors=data.errors.slice(0,100)}
function renderErrors(){const list=data.errors||[];document.getElementById('errorCount').textContent=list.length;const counts={};list.forEach(e=>counts[e.part]=(counts[e.part]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];document.getElementById('topWeak').textContent=top?'Part '+top[0]:'—';document.getElementById('reviewedCount').textContent=list.filter(e=>e.reviewed).length;document.getElementById('errorList').innerHTML=list.length?list.map(e=>`<div class="error-item"><b>Part ${e.part} · ${e.q}</b><small>正解：${e.ans}<br>${e.why}<br>錯因：${e.cause} · ${e.date}</small><div class="actions"><button class="btn ${e.reviewed?'btn-green':'btn-soft'}" onclick="toggleReviewed('${e.id}')">${e.reviewed?'✅ 已複習':'標記已複習'}</button></div></div>`).join(''):'<div class="empty">目前沒有錯題。開始限時訓練後，答錯的題會自動進來。</div>'}
function toggleReviewed(id){const e=data.errors.find(x=>String(x.id)===String(id));if(e)e.reviewed=!e.reviewed;save();renderErrors()}
function clearErrors(){if(confirm('確定清空錯題紀錄？')){data.errors=[];save();renderErrors()}}
function renderVocab(){const v=VOCAB[vIndex];const known=data.vocabKnown.includes(v.w);document.getElementById('vocabCard').innerHTML=`<span class="pill">${v.pos}</span><div class="vocab-word">${v.w} ${known?'✅':''}</div><div class="translation">${v.zh}</div><p><b>搭配：</b>${v.col}</p><div class="example"><b>${v.ex}</b><br><span style="color:var(--muted)">${v.exzh}</span></div><p class="hint">${vIndex+1} / ${VOCAB.length}</p>`;document.getElementById('vocabMastered').textContent=data.vocabKnown.length}
function prevVocab(){vIndex=(vIndex-1+VOCAB.length)%VOCAB.length;renderVocab()}function nextVocab(){vIndex=(vIndex+1)%VOCAB.length;renderVocab()}function speakVocab(){const v=VOCAB[vIndex];speak(v.w+'. '+v.ex,.72)}function gradeVocab(ok){const w=VOCAB[vIndex].w;if(ok&&!data.vocabKnown.includes(w))data.vocabKnown.push(w);if(!ok)data.vocabKnown=data.vocabKnown.filter(x=>x!==w);save();nextVocab()}
function renderProgress(){const days=Object.keys(data.history).length;document.getElementById('pDays').textContent=days;document.getElementById('pQuestions').textContent=data.practice.total||0;document.getElementById('pAccuracy').textContent=data.practice.total?Math.round(data.practice.correct/data.practice.total*100)+'%':'—';document.getElementById('pVocab').textContent=data.vocabKnown.length;const arr=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toLocaleDateString('en-CA');arr.push({label:['日','一','二','三','四','五','六'][d.getDay()],v:data.history[k]||0})}document.getElementById('weekChart').innerHTML=arr.map(x=>`<div class="barcol"><div class="bar" style="height:${Math.max(5,x.v*1.35)}px"></div><div>週${x.label}</div><div>${x.v}%</div></div>`).join('');let msg='先建立 7 天連續紀錄。每天至少完成一個限時訓練，系統才有資料判斷弱點。';if(data.practice.total>=30){const a=data.practice.correct/data.practice.total;msg=a>=.9?'累積正確率已進入 90% 區間。下一步提高 Part 7 閱讀速度與 Listening 一次聽懂率。':a>=.8?'基礎正確率不錯，但距離 950 的容錯率還不夠。優先重做錯題最多的 Part。':'目前應先追求準確率，不要急著壓時間。把錯因縮小到固定 2–3 類再集中擊破。'}document.getElementById('progressAdvice').textContent=msg}
function updateAll(){loadSettings();updateScoreUI();renderTasks();renderParts();renderVocab();renderErrors();renderProgress();updateDiagStats();document.body.classList.toggle('focus-mode',['practice','diagnostic'].some(id=>document.getElementById(id).classList.contains('active')));if(data.diag.i>=DIAG.length&&data.diag.answers.length)finishDiag()}
initDay();greeting();updateAll();
