const fs=require('fs'),vm=require('vm');
function assert(c,m){if(!c){console.error('FAIL:',m);process.exit(1)}}
const dataFiles=['data-core.js','data-listening.js','data-part5.js','data-part6.js','data-part7.js','data-expansion-core.js','data-expansion-listening.js','data-expansion-part5.js','data-expansion-reading.js','data-diversity-v2.js','data-diversity-contexts.js','data-diversity-cleanup.js'];
const store=new Map();const dummyEl=()=>({textContent:'',value:'720',classList:{add:()=>{},remove:()=>{}},querySelector:()=>null});
const ctx={console,Math,JSON,Set,Map,localStorage:{setItem:(k,v)=>store.set(k,String(v)),getItem:k=>store.has(k)?store.get(k):null,removeItem:k=>store.delete(k)},document:{getElementById:()=>dummyEl(),querySelector:()=>null},practice:{list:[],answers:[]},startPractice:()=>{},resetPractice:()=>{},chosenDifficulty:()=>720,prepareQuestion:q=>q,updateTimer:()=>{},renderPractice:()=>{},focusQuestionBox:()=>{},setInterval:()=>0,Date,shuffle:null};
vm.createContext(ctx);vm.runInContext(dataFiles.map(f=>fs.readFileSync(f,'utf8')).join('\n')+'\nglobalThis.__Q=QUESTIONS;',ctx);ctx.QUESTIONS=ctx.__Q;ctx.shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
vm.runInContext(fs.readFileSync('app-repeat-control.js','utf8')+'\nglobalThis.__r={diversePick,rememberQuestionExposure,clearQuestionCooldown,familyOf,groupKeyOf,structureOf,structureSimilarity};',ctx);const api=ctx.__r;
function strictFive(part){api.clearQuestionCooldown();const structuresSeen=[];const idsSeen=new Set();for(let round=1;round<=5;round++){const list=api.diversePick(part,720,10);assert(list.length===10,`Part ${part} round ${round}: expected 10`);const ids=new Set(list.map(q=>q.id)),structures=list.map(api.structureOf);assert(ids.size===10,`Part ${part}: duplicate ID inside round`);assert(new Set(structures).size===10,`Part ${part}: duplicate structure inside round`);for(let i=0;i<structures.length;i++)for(let j=i+1;j<structures.length;j++)assert(api.structureSimilarity(structures[i],structures[j])<.78,`Part ${part}: near-duplicate structure inside round`);for(const s of structures)for(const old of structuresSeen)assert(api.structureSimilarity(s,old)<.84,`Part ${part}: near-duplicate structure across first five rounds`);assert([...ids].every(id=>!idsSeen.has(id)),`Part ${part}: exact question repeated in first five rounds`);structuresSeen.push(...structures);ids.forEach(id=>idsSeen.add(id));api.rememberQuestionExposure(list)}assert(structuresSeen.length===50,`Part ${part}: expected 50 structures across five rounds`);return structuresSeen.length}
function groupedSanity(part){api.clearQuestionCooldown();let prevGroups=new Set();for(let round=1;round<=5;round++){const list=api.diversePick(part,720,10);assert(list.length===10,`Part ${part} round ${round}: expected 10`);const groups=new Set(list.map(api.groupKeyOf));assert(groups.size>=Math.ceil(10/4),`Part ${part}: too few conversation/document groups`);if(round>1)assert([...groups].every(g=>!prevGroups.has(g)),`Part ${part}: immediate document/conversation repeat`);prevGroups=groups;api.rememberQuestionExposure(list)}}
const p2=strictFive(2),p5=strictFive(5);for(const p of [3,4,6,7])groupedSanity(p);console.log(`PASS repeat-smoke: Part 2=${p2} structures, Part 5=${p5} structures across five rounds; grouped Parts avoid immediate document repeats`);
