const fs=require('fs'),vm=require('vm');
function assert(c,m){if(!c){console.error('FAIL:',m);process.exit(1)}}
const dataFiles=['data-core.js','data-listening.js','data-part5.js','data-part6.js','data-part7.js','data-expansion-core.js','data-expansion-listening.js','data-expansion-part5.js','data-expansion-reading.js','data-diversity-v2.js','data-diversity-cleanup.js','data.js'];
const store=new Map();const dummyEl=()=>({textContent:'',value:'720',classList:{add:()=>{},remove:()=>{}},querySelector:()=>null});
const ctx={console,Math,JSON,Set,Map,localStorage:{setItem:(k,v)=>store.set(k,String(v)),getItem:k=>store.has(k)?store.get(k):null,removeItem:k=>store.delete(k)},document:{getElementById:()=>dummyEl(),querySelector:()=>null},practice:{list:[],answers:[]},startPractice:()=>{},resetPractice:()=>{},chosenDifficulty:()=>720,prepareQuestion:q=>q,updateTimer:()=>{},renderPractice:()=>{},focusQuestionBox:()=>{},setInterval:()=>0,Date,shuffle:null};
vm.createContext(ctx);vm.runInContext(dataFiles.map(f=>fs.readFileSync(f,'utf8')).join('\n')+'\nglobalThis.__Q=QUESTIONS;',ctx);ctx.QUESTIONS=ctx.__Q;ctx.shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
vm.runInContext(fs.readFileSync('app-repeat-control.js','utf8')+'\nglobalThis.__r={diversePick,rememberQuestionExposure,clearQuestionCooldown,familyOf,groupKeyOf};',ctx);const api=ctx.__r;
function strictFive(part){api.clearQuestionCooldown();const familiesSeen=new Set(),idsSeen=new Set();for(let round=1;round<=5;round++){const list=api.diversePick(part,720,10);assert(list.length===10,`Part ${part} round ${round}: expected 10`);const ids=new Set(list.map(q=>q.id)),families=new Set(list.map(api.familyOf));assert(ids.size===10,`Part ${part}: duplicate ID inside round`);assert(families.size===10,`Part ${part}: duplicate structural family inside round`);assert([...families].every(f=>!familiesSeen.has(f)),`Part ${part} round ${round}: structural family repeated from an earlier round`);assert([...ids].every(id=>!idsSeen.has(id)),`Part ${part}: exact question repeated in first five rounds`);families.forEach(f=>familiesSeen.add(f));ids.forEach(id=>idsSeen.add(id));api.rememberQuestionExposure(list)}assert(familiesSeen.size===50,`Part ${part}: expected 50 structural families across five rounds`);return familiesSeen.size}
function groupedSanity(part){api.clearQuestionCooldown();let prevGroups=new Set();for(let round=1;round<=5;round++){const list=api.diversePick(part,720,10);assert(list.length===10,`Part ${part} round ${round}: expected 10`);const groups=new Set(list.map(api.groupKeyOf)),familiesByGroup=new Map();for(const q of list)familiesByGroup.set(api.groupKeyOf(q),api.familyOf(q));assert(new Set(familiesByGroup.values()).size===familiesByGroup.size,`Part ${part}: two different documents from same family inside one round`);if(round>1)assert([...groups].every(g=>!prevGroups.has(g)),`Part ${part}: immediate document/conversation repeat`);prevGroups=groups;api.rememberQuestionExposure(list)}}
const p2=strictFive(2),p5=strictFive(5);for(const p of [3,4,6,7])groupedSanity(p);console.log(`PASS repeat-smoke: Part 2=${p2} families, Part 5=${p5} families across five rounds; grouped Parts have no adjacent document repeat`);
